services:
  backend:
    image: playground-app-backend:latest
    networks:
      - testnet
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      update_config:
        parallelism: 1
        delay: 5s
  nginx:
    image: nginx:latest
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - target: 80
        published: 8081
        mode: ingress
        protocol: tcp
    networks:
      - testnet

networks:
  testnet:
    driver: overlay
    driver_opts:
      com.docker.network.driver.mtu: 1000